import { GitHubAggregatedData } from "./types";

export const MOCK_GITHUB_USERS: Record<string, GitHubAggregatedData> = {
  torvalds: {
    user: {
      login: "torvalds",
      id: 1024025,
      avatar_url: "https://avatars.githubusercontent.com/u/1024025?v=4",
      html_url: "https://github.com/torvalds",
      name: "Linus Torvalds",
      company: "Linux Foundation",
      blog: "",
      location: "Portland, OR",
      bio: "Creator of Linux and Git.",
      public_repos: 7,
      public_gists: 0,
      followers: 228000,
      following: 0,
      created_at: "2011-09-03T15:26:22Z",
      updated_at: "2026-08-10T11:00:00Z",
    },
    recentRepos: [
      {
        name: "linux",
        full_name: "torvalds/linux",
        description: "Linux kernel source tree",
        language: "C",
        stargazers_count: 185000,
        forks_count: 54000,
        updated_at: "2026-09-07T12:00:00Z",
        has_readme: true,
        topics: ["c", "kernel", "linux", "os"],
      },
      {
        name: "subsurface-for-dirk",
        full_name: "torvalds/subsurface-for-dirk",
        description: "Subsurface diving log software",
        language: "C",
        stargazers_count: 530,
        forks_count: 120,
        updated_at: "2026-07-15T09:00:00Z",
        has_readme: true,
        topics: ["scuba", "diving"],
      },
    ],
    languages: {
      C: 85,
      Assembly: 10,
      Shell: 5,
    },
    totalStars: 185530,
    totalForks: 54120,
    commitPatterns: {
      recentCommitCountEstimate: 420,
      sampleCommitMessages: [
        "Linux 6.16-rc7",
        "Merge tag 'x86_urgent_for_v6.16'",
        "drm/i915: fix panic on reboot",
        "Merge branch 'akpm' (patches from Andrew)",
      ],
    },
    analyzedAt: new Date().toISOString(),
    isMock: true,
  },

  "rookie-dev": {
    user: {
      login: "rookie-dev",
      id: 99887766,
      avatar_url: "https://avatars.githubusercontent.com/u/99887766?v=4",
      html_url: "https://github.com/rookie-dev",
      name: "코딩꿈나무",
      company: null,
      blog: "https://velog.io/@rookie",
      location: "Seoul, Korea",
      bio: "1일 1커밋 도전 중! 풀스택 지망생입니다.",
      public_repos: 18,
      public_gists: 2,
      followers: 12,
      following: 85,
      created_at: "2024-03-01T10:00:00Z",
      updated_at: "2026-09-05T14:30:00Z",
    },
    recentRepos: [
      {
        name: "my-todo-list-app",
        full_name: "rookie-dev/my-todo-list-app",
        description: "리액트로 처음 만든 투두리스트",
        language: "JavaScript",
        stargazers_count: 1,
        forks_count: 0,
        updated_at: "2026-09-05T14:30:00Z",
        has_readme: true,
        topics: ["react", "todo"],
      },
      {
        name: "algorithm-study",
        full_name: "rookie-dev/algorithm-study",
        description: "백준 파이썬 풀이 모음",
        language: "Python",
        stargazers_count: 2,
        forks_count: 0,
        updated_at: "2026-09-02T18:00:00Z",
        has_readme: false,
        topics: ["algorithm", "baekjoon"],
      },
      {
        name: "clone-netflix",
        full_name: "rookie-dev/clone-netflix",
        description: "넷플릭스 클론코딩 (작업중단)",
        language: "HTML",
        stargazers_count: 0,
        forks_count: 0,
        updated_at: "2024-05-10T12:00:00Z",
        has_readme: false,
        topics: ["clone"],
      },
    ],
    languages: {
      JavaScript: 45,
      Python: 35,
      HTML: 15,
      CSS: 5,
    },
    totalStars: 3,
    totalForks: 0,
    commitPatterns: {
      recentCommitCountEstimate: 14,
      sampleCommitMessages: [
        "fix",
        "fix typo",
        "제발 돼라",
        "update README",
        "Add: 투두리스트 버튼 수정",
        "버그 수정 완료",
      ],
    },
    analyzedAt: new Date().toISOString(),
    isMock: true,
  },
};

export const MOCK_GITHUB_REPOS: Record<string, import("./types").GitHubRepoDetailedData> = {
  "rome777/aiffel_test": {
    owner: {
      login: "rome777",
      avatar_url: "https://avatars.githubusercontent.com/u/18477511?v=4",
      html_url: "https://github.com/rome777",
    },
    name: "aiffel_test",
    full_name: "rome777/aiffel_test",
    description: "AI 기반 풀스택 웹 애플리케이션 및 지도/API 서비스 프로토타입",
    html_url: "https://github.com/rome777/aiffel_test",
    stargazers_count: 0,
    forks_count: 0,
    open_issues_count: 0,
    watchers_count: 0,
    default_branch: "main",
    size: 198,
    license: null,
    language: "HTML",
    languages: {
      HTML: 52,
      JavaScript: 30,
      Python: 18,
    },
    recentCommits: [
      {
        date: "2026-09-04T12:34:13Z",
        message: "배포 버튼 이미지 파일명 deploy.svg 로 변경 및 캐시 버스팅 적용",
        author: "rome777",
        hasCoAuthor: true,
        coAuthorNames: ["Claude Opus 5 <noreply@anthropic.com>"],
      },
      {
        date: "2026-09-04T12:32:31Z",
        message: "지도 버튼 스타일 그래디언트 및 SPEC.md 명세 준수 리팩토링",
        author: "rome777",
        hasCoAuthor: true,
        coAuthorNames: ["Claude Opus 5 <noreply@anthropic.com>"],
      },
      {
        date: "2026-09-04T12:25:12Z",
        message: "지도 타일 교체 및 Leaflet SDK 이슈 해결",
        author: "rome777",
        hasCoAuthor: true,
        coAuthorNames: ["Claude Opus 5 <noreply@anthropic.com>"],
      },
    ],
    files: [
      { name: "SPEC.md", type: "file", size: 4200 },
      { name: "SPEC-DETAIL.md", type: "file", size: 8500 },
      { name: "OPERATIONS.md", type: "file", size: 3100 },
      { name: "README.md", type: "file", size: 1200 },
      { name: "worker.js", type: "file", size: 3400 },
      { name: "server.py", type: "file", size: 2800 },
      { name: "build.mjs", type: "file", size: 1100 },
      { name: "wrangler.toml", type: "file", size: 450 },
      { name: "index.html", type: "file", size: 6200 },
      { name: ".claude", type: "dir" },
    ],
    targetFile: {
      name: "SPEC.md",
      path: "SPEC.md",
      size: 4200,
      contentPreview: "# Feature Specification\n- System Architecture: Cloudflare Workers + Python Server\n- Map Tile API: OpenStreetMap with custom dark filter\n- Deployment: Automated build via build.mjs",
    },
    hasReadme: true,
    hasSpecOrDocs: true,
    hasTests: false,
    hasCiCd: true,
    analyzedAt: new Date().toISOString(),
    isMock: true,
  },

  "facebook/react": {
    owner: {
      login: "facebook",
      avatar_url: "https://avatars.githubusercontent.com/u/69631?v=4",
      html_url: "https://github.com/facebook",
    },
    name: "react",
    full_name: "facebook/react",
    description: "The library for web and native user interfaces.",
    html_url: "https://github.com/facebook/react",
    stargazers_count: 228000,
    forks_count: 46000,
    open_issues_count: 1250,
    watchers_count: 6700,
    default_branch: "main",
    size: 340000,
    license: "MIT",
    language: "JavaScript",
    languages: {
      JavaScript: 85,
      TypeScript: 10,
      HTML: 3,
      CSS: 2,
    },
    recentCommits: [
      {
        date: "2026-09-07T18:00:00Z",
        message: "fix(compiler): handle memoization edge cases in nested loops",
        author: "acdlite",
        hasCoAuthor: false,
        coAuthorNames: [],
      },
      {
        date: "2026-09-06T15:30:00Z",
        message: "docs: update server actions reference",
        author: "gaearon",
        hasCoAuthor: false,
        coAuthorNames: [],
      },
    ],
    files: [
      { name: "README.md", type: "file" },
      { name: "packages", type: "dir" },
      { name: "scripts", type: "dir" },
      { name: ".github", type: "dir" },
      { name: "package.json", type: "file" },
      { name: "LICENSE", type: "file" },
    ],
    hasReadme: true,
    hasSpecOrDocs: true,
    hasTests: true,
    hasCiCd: true,
    analyzedAt: new Date().toISOString(),
    isMock: true,
  },
};
