import { EvaluationResult } from "./types";

export const MOCK_EVALUATIONS: Record<string, Record<"roast" | "review", EvaluationResult>> = {
  torvalds: {
    roast: {
      targetUsername: "torvalds",
      mode: "roast",
      tier: "SSS",
      score: 99,
      title: "인류 문명의 백엔드를 쥐고 흔드는 깃의 창조주",
      oneLiner: "C언어 하나로 전 세계 서버를 굴리시면서 아직도 남의 코드를 가차없이 갈아마시는 악마.",
      summary: "리포지토리가 7개밖에 안 되는데 스타 수가 18만 개가 넘는 비상식적인 계정입니다. 잔디가 비어 있어도 아무도 감히 '1일 1커밋 안 하세요?'라고 물어볼 수 없는 신계의 영역에 머물고 있습니다. 최신 프레임워크가 난무하는 시대에 묵직한 C언어 원툴로 세상을 지배 중입니다.",
      radarScores: {
        commitActivity: 95,
        documentation: 90,
        stackDiversity: 70,
        codePopularity: 100,
        consistency: 98,
      },
      highlights: [
        "스타 18만 개짜리 리포지토리 하나로 대한민국 IT 기업 전체 시총급 영향력 행사 중",
        "React가 뭔지 평생 몰라도 밥 먹고 사는데 1도 지장 없음",
        "커밋 메시지에 감정이 듬뿍 실려 있어 읽는 메인테이너 간담을 서늘하게 만듦",
      ],
      recommendations: [
        "가끔은 Rust도 한번 쳐다봐 주세요 (이미 리눅스 커널에 들어갔지만)",
        "후배 개발자들을 위해 조금만 덜 무섭게 메일링 리스트를 써주세요",
        "그냥 건강만 하시면 됩니다...",
      ],
      riskFactor: "깃허브가 망해도 이 분 코드는 살아남음 (0% 위험)",
      analyzedAt: new Date().toISOString(),
      isMock: true,
    },
    review: {
      targetUsername: "torvalds",
      mode: "review",
      tier: "SSS",
      score: 100,
      title: "오픈소스 생태계의 기념비적 테크 리더",
      oneLiner: "전 세계 소프트웨어 인프라의 기저를 지탱하는 최정상급 시스템 아키텍트.",
      summary: "리눅스 커널과 Git이라는 현대 소프트웨어 공학의 두 기둥을 직접 설계하고 30년 넘게 유지보수해 온 입지전적 아키텍트입니다. 방대한 코드베이스를 체계적으로 관리하는 거버넌스와 엄격한 코드 리뷰 기준은 전 세계 소프트웨어 엔지니어링의 표준입니다.",
      radarScores: {
        commitActivity: 98,
        documentation: 92,
        stackDiversity: 80,
        codePopularity: 100,
        consistency: 100,
      },
      highlights: [
        "리눅스 커널 프로젝트의 최고 메인테이너로서 독보적인 글로벌 리더십",
        "효율성과 성능을 극한으로 추구하는 C 언어 기반 시스템 아키텍처 역량",
        "30년 이상 중단 없는 지속적인 커밋 및 릴리즈 사이클 유지",
      ],
      recommendations: [
        "차세대 시스템 프로그래머 양성을 위한 멘토링 아카이브 권장",
        "커널 내부 서브시스템 문서의 현대화 및 시각적 다이어그램 확충 제안",
        "기존 아키텍처의 성공 사례를 담은 백서(Whitepaper) 발간 추천",
      ],
      riskFactor: "글로벌 테크 인프라 의존도 극상 (대체 불가능)",
      analyzedAt: new Date().toISOString(),
      isMock: true,
    },
  },

  "rookie-dev": {
    roast: {
      targetUsername: "rookie-dev",
      mode: "roast",
      tier: "D",
      score: 42,
      title: "사막화 직전의 튜토리얼 묘지기",
      oneLiner: "커밋 메시지 'fix' 12개, 클론 코딩 3개 중 완주율 0%, 잔디밭은 이미 황무지입니다.",
      summary: "의욕은 충만하여 넷플릭스, 인스타, 배민을 다 클론하려 했으나 1주일을 넘기지 못하고 깃허브를 방치했습니다. 잔디밭이 듬성듬성 탈모 온 것처럼 비어 있으며, 유일한 스타는 본인 부계정이 누른 것으로 추정됩니다.",
      radarScores: {
        commitActivity: 35,
        documentation: 20,
        stackDiversity: 50,
        codePopularity: 15,
        consistency: 25,
      },
      highlights: [
        "커밋 메시지가 'fix', '제발', '아왜안돼' 3단 콤보로 이루어짐",
        "README.md 파일은 리액트 기본 CRA 템플릿 그대로 방치 중",
        "포트폴리오 링크를 눌렀더니 '404 Vercel 배포 실패' 화면 출력",
      ],
      recommendations: [
        "제발 커밋 메시지에 무슨 짓을 했는지 한 줄이라도 적어주세요 (feat: ... fix: ...)",
        "새 프로젝트 시작 버튼 그만 누르고, 투두리스트 하나라도 배포까지 끝내보세요",
        "잔디 색칠 놀이 그만하고 실제 돌아가는 기능을 README에 GIF로 캡처해 넣으세요",
      ],
      riskFactor: "서류 탈락 광탈 위험도 89%",
      analyzedAt: new Date().toISOString(),
      isMock: true,
    },
    review: {
      targetUsername: "rookie-dev",
      mode: "review",
      tier: "C",
      score: 55,
      title: "성장 잠재력을 가진 초기 주니어 프론트엔드 지망생",
      oneLiner: "다양한 웹 기술 스택을 탐색하며 기초를 다지는 중이나, 프로젝트 완성도와 문서화 보완이 필요함.",
      summary: "React와 Python, JavaScript를 두루 접하며 기초 웹 프로그래밍 역량을 쌓아가고 있습니다. 다만 여러 튜토리얼 프로젝트가 미완성 상태로 남아 있어, 하나의 대표 프로젝트를 완성도 있게 끝까지 빌드업하는 과정이 필요합니다.",
      radarScores: {
        commitActivity: 45,
        documentation: 30,
        stackDiversity: 60,
        codePopularity: 20,
        consistency: 40,
      },
      highlights: [
        "React 및 알고리즘 학습을 병행하며 개발자로서의 기본기 습득에 집중하는 성실함",
        "Python과 JS 등 현대 웹 개발의 기초 언어군을 고루 경험함",
        "지속적인 학습 의지와 커밋 시도",
      ],
      recommendations: [
        "가장 애정이 가는 프로젝트 1개를 선정하여 상세 README 작성 (스크린샷, 기술 스택 선정 이유, 문제 해결 과정 기술)",
        "Git Conventional Commits 규칙을 준수하여 전문적인 커밋 이력 관리 습관 형성",
        "Vercel이나 Netlify를 활용한 라이브 데모 배포 링크를 리포지토리 상단에 등록",
      ],
      riskFactor: "포트폴리오 차별성 부족 (대표작 완성 시 급상승 가능)",
      analyzedAt: new Date().toISOString(),
      isMock: true,
    },
  },
};
